# Radius resource deployment plan
# Generated by Radius control plane
# Resource: frontend (Radius.Compute/containers)
# Generated: 2026-02-18T20:56:03Z

terraform {
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.0"
    }
  }
}

provider "kubernetes" {
  # Provider configuration is managed by the Radius control plane
}
