# Radius resource deployment plan
# Generated by Radius control plane
# Resource: frontend (Radius.Compute/containers)
# Generated: 2026-03-04T19:52:40Z

module "frontend" {
  source = "git::https://github.com/radius-project/resource-types-contrib.git//Compute/containers/recipes/azure/terraform"

  # Pass the Radius context to the recipe module
  context = var.context
}

# Outputs from the recipe module
output "result" {
  description = "Result output from the recipe module"
  value       = try(module.frontend.result, null)
  sensitive   = true
}
