# Radius resource deployment plan
# Generated by Radius control plane
# Variables for resource: db (Radius.Data/postgreSqlDatabases)
# Generated: 2026-02-18T23:47:28Z

variable "context" {
  description = "Radius recipe context containing resource, application, environment, and runtime information"
  type = object({
    resource = object({
      name       = string
      type       = string
      properties = any
      connections = optional(map(object({
        id         = string
        name       = string
        type       = string
        properties = optional(any)
      })), {})
    })
    application = object({
      name = string
    })
    environment = object({
      name = string
    })
    runtime = object({
      kubernetes = optional(object({
        namespace            = string
        environmentNamespace = string
      }))
    })
    azure = optional(object({
      resourceGroup = object({
        name = string
      })
      subscription = object({
        subscriptionId = string
      })
    }))
    aws = optional(object({
      region  = string
      account = string
    }))
  })
}
