# Radius resource deployment plan
# Generated by Radius control plane
# Resource: db (Radius.Data/postgreSqlDatabases)
# Generated: 2026-02-19T18:54:09Z

terraform {
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.0"
    }
  }
}

provider "kubernetes" {
  # Provider configuration is managed by the Radius control plane
}
