# Radius resource deployment plan
# Generated by Radius control plane
# Resource: db (Radius.Data/postgreSqlDatabases)
# Generated: 2026-02-19T19:06:49Z

module "db" {
  source = "git::https://github.com/radius-project/resource-types-contrib.git//Data/postgreSqlDatabases/recipes/azure/terraform"

  # Pass the Radius context to the recipe module
  context = var.context
}

# Outputs from the recipe module
output "result" {
  description = "Result output from the recipe module"
  value       = try(module.db.result, null)
  sensitive   = true
}
